name: nasa_api
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  http: ^1.2.1
  intl: ^0.19.0
  provider: ^6.1.2
  share: ^2.0.4
  path_provider: ^2.1.3
  flutter_staggered_grid_view: ^0.4.0
  firebase_remote_config: ^5.0.2
  firebase_core: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
