// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfZhGim-kSGdZK310OkTrcyT6CxOOC5Ic',
    appId: '1:973489000663:web:68d34cb073803049392092',
    messagingSenderId: '973489000663',
    projectId: 'nasa-api-study',
    authDomain: 'nasa-api-study.firebaseapp.com',
    storageBucket: 'nasa-api-study.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTV7y22rGw03US9z3u8ygCr6v5k9ZaTZo',
    appId: '1:973489000663:android:12bd1eec387f59a4392092',
    messagingSenderId: '973489000663',
    projectId: 'nasa-api-study',
    storageBucket: 'nasa-api-study.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARAEoJEK_JhZP8jNxI40vtTQhifQR34gI',
    appId: '1:973489000663:ios:3e64e98fa4ed5813392092',
    messagingSenderId: '973489000663',
    projectId: 'nasa-api-study',
    storageBucket: 'nasa-api-study.appspot.com',
    iosBundleId: 'com.example.nasaApi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARAEoJEK_JhZP8jNxI40vtTQhifQR34gI',
    appId: '1:973489000663:ios:3e64e98fa4ed5813392092',
    messagingSenderId: '973489000663',
    projectId: 'nasa-api-study',
    storageBucket: 'nasa-api-study.appspot.com',
    iosBundleId: 'com.example.nasaApi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfZhGim-kSGdZK310OkTrcyT6CxOOC5Ic',
    appId: '1:973489000663:web:22106305b7923e74392092',
    messagingSenderId: '973489000663',
    projectId: 'nasa-api-study',
    authDomain: 'nasa-api-study.firebaseapp.com',
    storageBucket: 'nasa-api-study.appspot.com',
  );
}
